### ISSUE TITLE
Страница SVG path - 404

### ISSUE THREAD

**Issue by sunnyphp** [yoksel/yoksel.github.io#12]
После сегодняшних изменений пропала страница с информацией об SVG path: https://yoksel.github.io/svg-path/.
Вчера еще была.

**Comment by yoksel** [comment]
@sunnyphp Да, небольшие технические шоколадки с некоторыми урлами. Без закрывающего слеша должно работать https://yoksel.github.io/svg-path

**Comment by yoksel** [comment]
Сейчас работает и со слешом
